name: education
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  golden_toolkit: ^0.9.0
  flutter_localization: ^0.2.0
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  provider: ^6.1.2
  riverpod: ^2.5.1
  hive: ^2.0.4
  flutter_countdown_timer: ^4.1.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.0.8
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^0.13.3
  mockito: ^5.0.0
  network_image_mock: ^2.1.1

arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
  fonts:
    - family: Coves
      fonts:
        - asset: assets/fonts/bold.otf
          weight: 700
        - asset: assets/fonts/light.otf
          weight: 400