name: Run tests

on:
  push:
    branches: [ lab7 ]
  pull_request:
    branches: [ lab7 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.4.1'

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test test.dart